In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
df = pd.read_csv('https://gist.githubusercontent.com/aishwarya8615/89d9f36fc014dea62487f7347864d16a/raw/8629d284e13976dcb13bb0b27043224b9266fffa/Life_Expectancy_Data.csv')

In [3]:
df

Country Continent  Year      Status  Life_expectancy   \
0     Afghanistan      Asia  2015  Developing              65.0   
1     Afghanistan      Asia  2014  Developing              59.9   
2     Afghanistan      Asia  2013  Developing              59.9   
3     Afghanistan      Asia  2012  Developing              59.5   
4     Afghanistan      Asia  2011  Developing              59.2   
...           ...       ...   ...         ...               ...   
2456     Zimbabwe    Africa  2004  Developing              44.3   
2457     Zimbabwe    Africa  2003  Developing              44.5   
2458     Zimbabwe    Africa  2002  Developing              44.8   
2459     Zimbabwe    Africa  2001  Developing              45.3   
2460     Zimbabwe    Africa  2000  Developing              46.0   

      Adult_Mortality  infant_deaths  Alcohol  percentage_expenditure  \
0                 263             62     0.01               71.279624   
1                 271             64     0.01               73.523582   
2                 268             66     0.01               73.219243   
3                 272             69     0.01               78.184215   
4                 275             71     0.01                7.097109   
...               ...            ...      ...                     ...   
2456              723             27     4.36                0.000000   
2457              715             26     4.06                0.000000   
2458               73             25     4.43                0.000000   
2459              686             25     1.72                0.000000   
2460              665             24     1.68                0.000000   

      Hepatitis_B  ...  Polio  Total_expenditure  Diphtheria    HIV/AIDS  \
0            65.0  ...    6.0               8.16           65        0.1   
1            62.0  ...   58.0               8.18           62        0.1   
2            64.0  ...   62.0               8.13           64        0.1   
3            67.0  ...   67.0               8.52           67        0.1   
4            68.0  ...   68.0               7.87           68        0.1   
...           ...  ...    ...                ...          ...        ...   
2456         68.0  ...   67.0               7.13           65       33.6   
2457          7.0  ...    7.0               6.52           68       36.7   
2458         73.0  ...   73.0               6.53           71       39.8   
2459         76.0  ...   76.0               6.16           75       42.1   
2460         79.0  ...   78.0               7.10           78       43.5   

             GDP Population   thinness  1-19 years   thinness 5-9 years  \
0     584.259210   33736494                   17.2                 17.3   
1     612.696514     327582                   17.5                 17.5   
2     631.744976   31731688                   17.7                 17.7   
3     669.959000    3696958                   17.9                 18.0   
4      63.537231    2978599                   18.2                 18.2   
...          ...        ...                    ...                  ...   
2456  454.366654   12777511                    9.4                  9.4   
2457  453.351155   12633897                    9.8                  9.9   
2458   57.348340     125525                    1.2                  1.3   
2459  548.587312   12366165                    1.6                  1.7   
2460  547.358878   12222251                   11.0                 11.2   

     Income_composition_of_resources  Schooling  
0                              0.479       10.1  
1                              0.476       10.0  
2                              0.470        9.9  
3                              0.463        9.8  
4                              0.454        9.5  
...                              ...        ...  
2456                           0.407        9.2  
2457                           0.418        9.5  
2458                           0.427       10.0  
2459          

In [4]:
df.replace({'Developing':0,'Developed': 1},inplace =True)

In [5]:
df

Country Continent  Year  Status  Life_expectancy   Adult_Mortality  \
0     Afghanistan      Asia  2015       0              65.0              263   
1     Afghanistan      Asia  2014       0              59.9              271   
2     Afghanistan      Asia  2013       0              59.9              268   
3     Afghanistan      Asia  2012       0              59.5              272   
4     Afghanistan      Asia  2011       0              59.2              275   
...           ...       ...   ...     ...               ...              ...   
2456     Zimbabwe    Africa  2004       0              44.3              723   
2457     Zimbabwe    Africa  2003       0              44.5              715   
2458     Zimbabwe    Africa  2002       0              44.8               73   
2459     Zimbabwe    Africa  2001       0              45.3              686   
2460     Zimbabwe    Africa  2000       0              46.0              665   

      infant_deaths  Alcohol  percentage_expenditure  Hepatitis_B  ...  Polio  \
0                62     0.01               71.279624         65.0  ...    6.0   
1                64     0.01               73.523582         62.0  ...   58.0   
2                66     0.01               73.219243         64.0  ...   62.0   
3                69     0.01               78.184215         67.0  ...   67.0   
4                71     0.01                7.097109         68.0  ...   68.0   
...             ...      ...                     ...          ...  ...    ...   
2456             27     4.36                0.000000         68.0  ...   67.0   
2457             26     4.06                0.000000          7.0  ...    7.0   
2458             25     4.43                0.000000         73.0  ...   73.0   
2459             25     1.72                0.000000         76.0  ...   76.0   
2460             24     1.68                0.000000         79.0  ...   78.0   

      Total_expenditure  Diphtheria    HIV/AIDS         GDP Population  \
0                  8.16           65        0.1  584.259210   33736494   
1                  8.18           62        0.1  612.696514     327582   
2                  8.13           64        0.1  631.744976   31731688   
3                  8.52           67        0.1  669.959000    3696958   
4                  7.87           68        0.1   63.537231    2978599   
...                 ...          ...        ...         ...        ...   
2456               7.13           65       33.6  454.366654   12777511   
2457               6.52           68       36.7  453.351155   12633897   
2458               6.53           71       39.8   57.348340     125525   
2459               6.16           75       42.1  548.587312   12366165   
2460               7.10           78       43.5  547.358878   12222251   

       thinness  1-19 years   thinness 5-9 years  \
0                      17.2                 17.3   
1                      17.5                 17.5   
2                      17.7                 17.7   
3                      17.9                 18.0   
4                      18.2                 18.2   
...                     ...                  ...   
2456                    9.4                  9.4   
2457                    9.8                  9.9   
2458                    1.2                  1.3   
2459                    1.6                  1.7   
2460                   11.0                 11.2   

     Income_composition_of_resources  Schooling  
0                              0.479       10.1  
1                              0.476       10.0  
2                              0.470        9.9  
3                              0.463        9.8  
4                              0.454        9.5  
...                              ...        ...  
2456                           0.407        9.2  
2457                           0.418        9.5  
2458                           0.427       10.0  
2459                           0.427        9.8  
2460        

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2461 entries, 0 to 2460
Data columns (total 23 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Country                          2461 non-null   object 
 1   Continent                        2461 non-null   object 
 2   Year                             2461 non-null   int64  
 3   Status                           2461 non-null   int64  
 4   Life_expectancy                  2461 non-null   float64
 5   Adult_Mortality                  2461 non-null   int64  
 6   infant_deaths                    2461 non-null   int64  
 7   Alcohol                          2461 non-null   float64
 8   percentage_expenditure           2461 non-null   float64
 9   Hepatitis_B                      1997 non-null   float64
 10  Measles                          2461 non-null   int64  
 11   BMI                             2461 non-null   float64
 12  under_five_deaths   

In [7]:
df.isnull().sum()

Country                              0
Continent                            0
Year                                 0
Status                               0
Life_expectancy                      0
Adult_Mortality                      0
infant_deaths                        0
Alcohol                              0
percentage_expenditure               0
Hepatitis_B                        464
Measles                              0
 BMI                                 0
under_five_deaths                    0
Polio                                8
Total_expenditure                  152
Diphtheria                           0
 HIV/AIDS                            0
GDP                                  0
Population                           0
 thinness  1-19 years                0
 thinness 5-9 years                  0
Income_composition_of_resources      3
Schooling                            3
dtype: int64

In [8]:
df['Hepatitis_B'].fillna(df['Hepatitis_B'].mean(),inplace =True)

In [9]:
df['Total_expenditure'].fillna(df['Total_expenditure'].mean(),inplace =True)
df['Income_composition_of_resources'].fillna(df['Income_composition_of_resources'].mean(),inplace =True)
df['Schooling'].fillna(df['Schooling'].mean(),inplace =True)
df['Polio'].fillna(df['Polio'].mean(),inplace =True)

In [10]:
df.isnull().sum()

Country                            0
Continent                          0
Year                               0
Status                             0
Life_expectancy                    0
Adult_Mortality                    0
infant_deaths                      0
Alcohol                            0
percentage_expenditure             0
Hepatitis_B                        0
Measles                            0
 BMI                               0
under_five_deaths                  0
Polio                              0
Total_expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income_composition_of_resources    0
Schooling                          0
dtype: int64

In [11]:
# prompt: take each column separate as x1,x2....xn skip continent and country and status as y

y = df['Status']
x1 = df['Life_expectancy '].values.reshape(-1, 1)
x2 = df['Adult_Mortality'].values.reshape(-1, 1)
x3 = df['infant_deaths'].values.reshape(-1, 1)
x4 = df['Alcohol'].values.reshape(-1, 1)
x5 = df['percentage_expenditure'].values.reshape(-1, 1)
x6 = df['Hepatitis_B'].values.reshape(-1, 1)
x7 = df['Measles '].values.reshape(-1, 1)
x8 = df[' BMI '].values.reshape(-1, 1)
x9 = df['under_five_deaths '].values.reshape(-1, 1)
x10 = df['Polio'].values.reshape(-1, 1)
x11 = df['Total_expenditure'].values.reshape(-1, 1)
x12 = df['Diphtheria '].values.reshape(-1, 1)
x13 = df[' HIV/AIDS'].values.reshape(-1, 1)
x14 = df['GDP'].values.reshape(-1, 1)
x15 = df['Population'].values.reshape(-1, 1)
x16 = df[' thinness  1-19 years'].values.reshape(-1, 1)
x17 = df[' thinness 5-9 years'].values.reshape(-1, 1)
x18 = df['Income_composition_of_resources'].values.reshape(-1, 1)
x19 = df['Schooling'].values.reshape(-1, 1)


In [12]:
df.columns

Index(['Country', 'Continent', 'Year', 'Status', 'Life_expectancy ',
       'Adult_Mortality', 'infant_deaths', 'Alcohol', 'percentage_expenditure',
       'Hepatitis_B', 'Measles ', ' BMI ', 'under_five_deaths ', 'Polio',
       'Total_expenditure', 'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income_composition_of_resources', 'Schooling'],
      dtype='object')

In [13]:
model = LogisticRegression()

In [14]:
# Replace 'Unknown' with a suitable value (e.g., mean)
mean_diphtheria = df['Diphtheria '][df['Diphtheria '] != 'Unknown'].astype(float).mean()
df['Diphtheria '] = df['Diphtheria '].replace('Unknown', mean_diphtheria)

# Convert the column to integers
df['Diphtheria '] = df['Diphtheria '].astype(int)

In [15]:
df.columns

Index(['Country', 'Continent', 'Year', 'Status', 'Life_expectancy ',
       'Adult_Mortality', 'infant_deaths', 'Alcohol', 'percentage_expenditure',
       'Hepatitis_B', 'Measles ', ' BMI ', 'under_five_deaths ', 'Polio',
       'Total_expenditure', 'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income_composition_of_resources', 'Schooling'],
      dtype='object')

In [18]:
model.fit(x1,y)
model.fit(x2,y)
model.fit(x3,y)
model.fit(x4,y)
model.fit(x5,y)
model.fit(x6,y)
model.fit(x7,y)
model.fit(x8,y)
model.fit(x9,y)
model.fit(x10,y)
model.fit(x11,y)
# model.fit(x12,y)
model.fit(x13,y)
model.fit(x14,y)
# model.fit(x15,y)
model.fit(x16,y)
model.fit(x17,y)
model.fit(x18,y)
model.fit(x19,y)

LogisticRegression()

In [19]:
# prompt: ypred for every modelfit

ypred1 = model.predict(x1)
ypred2 = model.predict(x2)
ypred3 = model.predict(x3)
ypred4 = model.predict(x4)
ypred5 = model.predict(x5)
ypred6 = model.predict(x6)
ypred7 = model.predict(x7)
ypred8 = model.predict(x8)
ypred9 = model.predict(x9)
ypred10 = model.predict(x10)
ypred11 = model.predict(x11)
# ypred12 = model.predict(x12)
ypred13 = model.predict(x13)
ypred14 = model.predict(x14)
# ypred15 = model.predict(x15)
ypred16 = model.predict(x16)
ypred17 = model.predict(x17)
ypred18 = model.predict(x18)
ypred19 = model.predict(x19)


In [20]:


print("Accuracy score for Life_expectancy: ",accuracy_score(y,ypred1))
print("Accuracy score for Adult_Mortality: ",accuracy_score(y,ypred2))
print("Accuracy score for infant_deaths: ",accuracy_score(y,ypred3))
print("Accuracy score for Alcohol: ",accuracy_score(y,ypred4))
print("Accuracy score for percentage_expenditure: ",accuracy_score(y,ypred5))
print("Accuracy score for Hepatitis_B: ",accuracy_score(y,ypred6))
print("Accuracy score for Measles: ",accuracy_score(y,ypred7))
print("Accuracy score for BMI: ",accuracy_score(y,ypred8))
print("Accuracy score for under_five_deaths: ",accuracy_score(y,ypred9))
print("Accuracy score for Polio: ",accuracy_score(y,ypred10))
print("Accuracy score for Total_expenditure: ",accuracy_score(y,ypred11))
# print("Accuracy score for Diphtheria: ",accuracy_score(y,ypred12))
print("Accuracy score for HIV/AIDS: ",accuracy_score(y,ypred13))
print("Accuracy score for GDP: ",accuracy_score(y,ypred14))
# print("Accuracy score for Population: ",accuracy_score(y,ypred15))
print("Accuracy score for thinness  1-19 years: ",accuracy_score(y,ypred16))
print("Accuracy score for thinness 5-9 years: ",accuracy_score(y,ypred17))
print("Accuracy score for Income_composition_of_resources: ",accuracy_score(y,ypred18))
print("Accuracy score for Schooling: ",accuracy_score(y,ypred19))


Accuracy score for Life_expectancy:  0.18203982121088988
Accuracy score for Adult_Mortality:  0.21698496546119464
Accuracy score for infant_deaths:  0.5444941080861438
Accuracy score for Alcohol:  0.8159284843559529
Accuracy score for percentage_expenditure:  0.3522958147094677
Accuracy score for Hepatitis_B:  0.22673709874034945
Accuracy score for Measles:  0.48923201950426654
Accuracy score for BMI:  0.3023161316537993
Accuracy score for under_five_deaths:  0.5209264526615197
Accuracy score for Polio:  0.23486387647297846
Accuracy score for Total_expenditure:  0.8179601787891101
Accuracy score for HIV/AIDS:  0.7862657456318569
Accuracy score for GDP:  0.18813490451036163
Accuracy score for thinness  1-19 years:  0.7834213734254368
Accuracy score for thinness 5-9 years:  0.7822023567655425
Accuracy score for Income_composition_of_resources:  0.8179601787891101
Accuracy score for Schooling:  0.8711905729378302


In [21]:
# prompt: confusion matrix

print("Confusion Matrix for Life_expectancy: \n",confusion_matrix(y,ypred1))
print("Confusion Matrix for Adult_Mortality: \n",confusion_matrix(y,ypred2))
print("Confusion Matrix for infant_deaths: \n",confusion_matrix(y,ypred3))
print("Confusion Matrix for Alcohol: \n",confusion_matrix(y,ypred4))
print("Confusion Matrix for percentage_expenditure: \n",confusion_matrix(y,ypred5))
print("Confusion Matrix for Hepatitis_B: \n",confusion_matrix(y,ypred6))
print("Confusion Matrix for Measles: \n",confusion_matrix(y,ypred7))
print("Confusion Matrix for BMI: \n",confusion_matrix(y,ypred8))
print("Confusion Matrix for under_five_deaths: \n",confusion_matrix(y,ypred9))
print("Confusion Matrix for Polio: \n",confusion_matrix(y,ypred10))
print("Confusion Matrix for Total_expenditure: \n",confusion_matrix(y,ypred11))
# print("Confusion Matrix for Diphtheria: \n",confusion_matrix(y,ypred12))
print("Confusion Matrix for HIV/AIDS: \n",confusion_matrix(y,ypred13))
print("Confusion Matrix for GDP: \n",confusion_matrix(y,ypred14))
# print("Confusion Matrix for Population: \n",confusion_matrix(y,ypred15))
print("Confusion Matrix for thinness  1-19 years: \n",confusion_matrix(y,ypred16))
print("Confusion Matrix for thinness 5-9 years: \n",confusion_matrix(y,ypred17))
print("Confusion Matrix for Income_composition_of_resources: \n",confusion_matrix(y,ypred18))
print("Confusion Matrix for Schooling: \n",confusion_matrix(y,ypred19))


Confusion Matrix for Life_expectancy: 
 [[   0 2013]
 [   0  448]]
Confusion Matrix for Adult_Mortality: 
 [[ 141 1872]
 [  55  393]]
Confusion Matrix for infant_deaths: 
 [[1340  673]
 [ 448    0]]
Confusion Matrix for Alcohol: 
 [[2008    5]
 [ 448    0]]
Confusion Matrix for percentage_expenditure: 
 [[ 458 1555]
 [  39  409]]
Confusion Matrix for Hepatitis_B: 
 [[ 125 1888]
 [  15  433]]
Confusion Matrix for Measles: 
 [[1000 1013]
 [ 244  204]]
Confusion Matrix for BMI: 
 [[ 340 1673]
 [  44  404]]
Confusion Matrix for under_five_deaths: 
 [[1282  731]
 [ 448    0]]
Confusion Matrix for Polio: 
 [[ 135 1878]
 [   5  443]]
Confusion Matrix for Total_expenditure: 
 [[2013    0]
 [ 448    0]]
Confusion Matrix for HIV/AIDS: 
 [[1935   78]
 [ 448    0]]
Confusion Matrix for GDP: 
 [[  16 1997]
 [   1  447]]
Confusion Matrix for thinness  1-19 years: 
 [[1928   85]
 [ 448    0]]
Confusion Matrix for thinness 5-9 years: 
 [[1925   88]
 [ 448    0]]
Confusion Matrix for Income_composition