In [2]:
vec = [[1,2,3],[4,5,6],[7,8,9]]
print(vec)
type(vec)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [3]:
import numpy as np

In [4]:
len(vec)

3

In [5]:
vec[2][1]

8

In [16]:
for i in vec:
    print(i)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [31]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3],[1, 2, 3], [4, 5, 6]])

print(arr1)

print(type(arr1))

print(arr2)

print(type(arr2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [25]:
x = np.add(arr1,arr2)
x

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [11, 13, 15]])

In [27]:
y = np.subtract(arr1,arr2)
y

array([[0, 0, 0],
       [3, 3, 3],
       [3, 3, 3]])

In [28]:
 np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [28, 40, 54]])

In [30]:
 np.transpose(arr1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [32]:
 np.dot(arr1,arr2)

array([[15, 21, 27],
       [33, 48, 63],
       [51, 75, 99]])

In [35]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [34]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
# Inverse a matrix
# Given a square matrix a 
#, return a matrix ainv satisfying dot(a, ainv)
#         = dot(ainv, a) = eye(a.shape[0]).
a = np.array([
    [2,1,0],
    [0,1,0],
    [1,2,1],
])
print(a, end= '= a\n')
print(np.linalg.inv(a), end='  =  |a|')

[[2 1 0]
 [0 1 0]
 [1 2 1]]= a
[[ 0.5 -0.5  0. ]
 [ 0.   1.   0. ]
 [-0.5 -1.5  1. ]]  =  |a|

In [39]:

#gradient descent

cur_x =5
rate =0.1
precision =0.5
previous_step_size = 1
max_iters = 10000000
iters =0

df = lambda x: 2*(x+5)

while previous_step_size > precision and iters < max_iters:
    prev_x = cur_x
    cur_x = cur_x - rate * df(prev_x)
    previous_step_size = abs(cur_x - prev_x)
    iters = iters +1
    print("Iteration",iters,"\n value is ", cur_x)

print("The local minimum occurs at",cur_x)

Iteration 1 
 value is  3.0
Iteration 2 
 value is  1.4
Iteration 3 
 value is  0.11999999999999966
Iteration 4 
 value is  -0.9040000000000001
Iteration 5 
 value is  -1.7232000000000003
Iteration 6 
 value is  -2.3785600000000002
Iteration 7 
 value is  -2.902848
Iteration 8 
 value is  -3.3222784
The local minimum occurs at -3.3222784
